name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]

jobs:
  lint:
    name: Run tests, Lint, and check format.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno lint
      - run: deno fmt --check
      - run: deno test --allow-write --allow-read --allow-run --allow-import
